version: '3.8'

services:
  web:
    build: ./evo
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./evo/:/usr/src/evo/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

volumes:
  postgres_data: